### ISSUE TITLE
Request-URI Too Long

### ISSUE THREAD

**Issue by KloonDuino** [myparcelnl/woocommerce-myparcel#10]
Beetje teveel van het goede ;)

Gebeurt als ik in de backend een filter gebruik op klant.
[afbeelding](https://i.imgsafe.org/59419ba83b.png)
Dus op `https://xxx.nl/wp-admin/edit.php?post_type=shop_order` doe ik een filter toevoegen en dan krijg ik de melding: `Request-URI Too Long`

Dit is de url die ik krijg als ik op het 'filter' submit knopje druk.

`https://xxxxx.nl/wp-admin/edit.php?s=&post_status=all&post_type=shop_order&_wpnonce=533e653791&_wp_http_referer=%2Fwp-admin%2Fedit.php%3Fpost_type%3Dshop_order&action=-1&m=0&_email_id=&_customer_user=709&filter_action=Filter&paged=1&myparcel_options%5B15630%5D%5Bpackage_type%5D=3&myparcel_options%5B15630%5D%5Binsured_amount%5D=49&myparcel_options%5B15630%5D%5Binsured_amount%5D=0&myparcel_options%5B15628%5D%5Bpackage_type%5D=2&myparcel_options%5B15628%5D%5Binsured_amount%5D=49&myparcel_options%5B15628%5D%5Binsured_amount%5D=0&myparcel_options%5B15615%5D%5Bpackage_type%5D=2&myparcel_options%5B15615%5D%5Binsured_amount%5D=49&myparcel_options%5B15615%5D%5Binsured_amount%5D=0&myparcel_options%5B15608%5D%5Bpackage_type%5D=2&myparcel_options%5B15608%5D%5Binsured_amount%5D=49&myparcel_options%5B15608%5D%5Binsured_amount%5D=0&myparcel_options%5B15606%5D%5Bpackage_type%5D=3&myparcel_options%5B15606%5D%5Binsured_amount%5D=49&myparcel_options%5B15606%5D%5Binsured_amount%5D=0&myparcel_options%5B15579%5D%5Bpackage_type%5D=3&myparcel_options%5B15579%5D%5Binsured_amount%5D=49&myparcel_options%5B15579%5D%5Binsured_amount%5D=0&myparcel_options%5B15530%5D%5Bpackage_type%5D=2&myparcel_options%5B15530%5D%5Binsured_amount%5D=49&myparcel_options%5B15530%5D%5Binsured_amount%5D=0&myparcel_options%5B15511%5D%5Bpackage_type%5D=2&myparcel_options%5B15511%5D%5Binsured_amount%5D=49&myparcel_options%5B15511%5D%5Binsured_amount%5D=0&myparcel_options%5B15497%5D%5Bpackage_type%5D=2&myparcel_options%5B15497%5D%5Binsured_amount%5D=49&myparcel_options%5B15497%5D%5Binsured_amount%5D=0&myparcel_options%5B15456%5D%5Bpackage_type%5D=2&myparcel_options%5B15456%5D%5Binsured_amount%5D=49&myparcel_options%5B15456%5D%5Binsured_amount%5D=0&myparcel_options%5B15452%5D%5Bpackage_type%5D=3&myparcel_options%5B15452%5D%5Binsured_amount%5D=49&myparcel_options%5B15452%5D%5Binsured_amount%5D=0&myparcel_options%5B15447%5D%5Bpackage_type%5D=2&myparcel_options%5B15447%5D%5Binsured_amount%5D=49&myparcel_options%5B15447%5D%5Binsured_amount%5D=0&myparcel_options%5B15437%5D%5Bpackage_type%5D=2&myparcel_options%5B15437%5D%5Binsured_amount%5D=49&myparcel_options%5B15437%5D%5Binsured_amount%5D=0&myparcel_options%5B15434%5D%5Bpackage_type%5D=2&myparcel_options%5B15434%5D%5Binsured_amount%5D=49&myparcel_options%5B15434%5D%5Binsured_amount%5D=0&myparcel_options%5B15253%5D%5Bpackage_type%5D=1&myparcel_options%5B15253%5D%5Binsured_amount%5D=49&myparcel_options%5B15253%5D%5Binsured_amount%5D=0&myparcel_options%5B15248%5D%5Bpackage_type%5D=2&myparcel_options%5B15248%5D%5Binsured_amount%5D=49&myparcel_options%5B15248%5D%5Binsured_amount%5D=0&myparcel_options%5B15245%5D%5Bpackage_type%5D=2&myparcel_options%5B15245%5D%5Binsured_amount%5D=49&myparcel_options%5B15245%5D%5Binsured_amount%5D=0&myparcel_options%5B15241%5D%5Bpackage_type%5D=2&myparcel_options%5B15241%5D%5Binsured_amount%5D=49&myparcel_options%5B15241%5D%5Binsured_amount%5D=0&myparcel_options%5B15239%5D%5Bpackage_type%5D=2&myparcel_options%5B15239%5D%5Binsured_amount%5D=49&myparcel_options%5B15239%5D%5Binsured_amount%5D=0&myparcel_options%5B15220%5D%5Bpackage_type%5D=2&myparcel_options%5B15220%5D%5Binsured_amount%5D=49&myparcel_options%5B15220%5D%5Binsured_amount%5D=0&myparcel_options%5B15216%5D%5Bpackage_type%5D=2&myparcel_options%5B15216%5D%5Binsured_amount%5D=49&myparcel_options%5B15216%5D%5Binsured_amount%5D=0&myparcel_options%5B15207%5D%5Bpackage_type%5D=2&myparcel_options%5B15207%5D%5Binsured_amount%5D=49&myparcel_options%5B15207%5D%5Binsured_amount%5D=0&myparcel_options%5B15196%5D%5Bpackage_type%5D=1&myparcel_options%5B15196%5D%5Binsured_amount%5D=49&myparcel_options%5B15196%5D%5Binsured_amount%5D=0&myparcel_options%5B15194%5D%5Bpackage_type%5D=2&myparcel_options%5B15194%5D%5Binsured_amount%5D=49&myparcel_options%5B15194%5D%5Binsured_amount%5D=0&myparcel_options%5B15189%5D%5Bpackage_type%5D=2&myparcel_options%5B15189%5D%5Binsured_amount%5D=49&myparcel_options%5B15189%5D%5Binsured_amount%5D=0&myparcel_options%5B15179%5D%5Bpackage_type%5D=2&myparcel_options%5B15179%5D%5Binsured_amount%5D=49&myparcel_options%5B15179%5D%5Binsured_amount%5D=0&myparcel_options%5B15175%5D%5Bpackage_type%5D=2&myparcel_options%5B15175%5D%5Binsured_amount%5D=49&myparcel_options%5B15175%5D%5Binsured_amount%5D=0&myparcel_options%5B15160%5D%5Bpackage_type%5D=2&myparcel_options%5B15160%5D%5Binsured_amount%5D=49&myparcel_options%5B15160%5D%5Binsured_amount%5D=0&myparcel_options%5B15158%5D%5Bpackage_type%5D=2&myparcel_options%5B15158%5D%5Binsured_amount%5D=49&myparcel_options%5B15158%5D%5Binsured_amount%5D=0&myparcel_options%5B15133%5D%5Bpackage_type%5D=1&myparcel_options%5B15133%5D%5Binsured_amount%5D=49&myparcel_options%5B15133%5D%5Binsured_amount%5D=0&myparcel_options%5B15120%5D%5Bpackage_type%5D=2&myparcel_options%5B15120%5D%5Binsured_amount%5D=49&myparcel_options%5B15120%5D%5Binsured_amount%5D=0&myparcel_options%5B15118%5D%5Bpackage_type%5D=1&myparcel_options%5B15118%5D%5Binsured_amount%5D=49&myparcel_options%5B15118%5D%5Binsured_amount%5D=0&myparcel_options%5B15105%5D%5Bpackage_type%5D=1&myparcel_options%5B15105%5D%5Binsured_amount%5D=49&myparcel_options%5B15105%5D%5Binsured_amount%5D=0&myparcel_options%5B15069%5D%5Bpackage_type%5D=2&myparcel_options%5B15069%5D%5Binsured_amount%5D=49&myparcel_options%5B15069%5D%5Binsured_amount%5D=0&myparcel_options%5B15063%5D%5Bpackage_type%5D=2&myparcel_options%5B15063%5D%5Binsured_amount%5D=49&myparcel_options%5B15063%5D%5Binsured_amount%5D=0&myparcel_options%5B15045%5D%5Bpackage_type%5D=2&myparcel_options%5B15045%5D%5Binsured_amount%5D=49&myparcel_options%5B15045%5D%5Binsured_amount%5D=0&myparcel_options%5B15022%5D%5Bpackage_type%5D=2&myparcel_options%5B15022%5D%5Binsured_amount%5D=49&myparcel_options%5B15022%5D%5Binsured_amount%5D=0&myparcel_options%5B15019%5D%5Bpackage_type%5D=2&myparcel_options%5B15019%5D%5Binsured_amount%5D=49&myparcel_options%5B15019%5D%5Binsured_amount%5D=0&myparcel_options%5B15012%5D%5Bpackage_type%5D=1&myparcel_options%5B15012%5D%5Binsured_amount%5D=49&myparcel_options%5B15012%5D%5Binsured_amount%5D=0&myparcel_options%5B15002%5D%5Bpackage_type%5D=2&myparcel_options%5B15002%5D%5Binsured_amount%5D=49&myparcel_options%5B15002%5D%5Binsured_amount%5D=0&myparcel_options%5B14971%5D%5Bpackage_type%5D=2&myparcel_options%5B14971%5D%5Binsured_amount%5D=49&myparcel_options%5B14971%5D%5Binsured_amount%5D=0&myparcel_options%5B14961%5D%5Bpackage_type%5D=2&myparcel_options%5B14961%5D%5Binsured_amount%5D=49&myparcel_options%5B14961%5D%5Binsured_amount%5D=0&myparcel_options%5B14920%5D%5Bpackage_type%5D=2&myparcel_options%5B14920%5D%5Binsured_amount%5D=49&myparcel_options%5B14920%5D%5Binsured_amount%5D=0&myparcel_options%5B14787%5D%5Bpackage_type%5D=2&myparcel_options%5B14787%5D%5Binsured_amount%5D=49&myparcel_options%5B14787%5D%5Binsured_amount%5D=0&myparcel_options%5B14473%5D%5Bpackage_type%5D=2&myparcel_options%5B14473%5D%5Binsured_amount%5D=49&myparcel_options%5B14473%5D%5Binsured_amount%5D=0&myparcel_options%5B12965%5D%5Bpackage_type%5D=2&myparcel_options%5B12965%5D%5Binsured_amount%5D=49&myparcel_options%5B12965%5D%5Binsured_amount%5D=0&myparcel_options%5B12908%5D%5Bpackage_type%5D=2&myparcel_options%5B12908%5D%5Binsured_amount%5D=49&myparcel_options%5B12908%5D%5Binsured_amount%5D=0&myparcel_options%5B12463%5D%5Bpackage_type%5D=2&myparcel_options%5B12463%5D%5Binsured_amount%5D=49&myparcel_options%5B12463%5D%5Binsured_amount%5D=0&myparcel_options%5B12433%5D%5Bpackage_type%5D=2&myparcel_options%5B12433%5D%5Binsured_amount%5D=49&myparcel_options%5B12433%5D%5Binsured_amount%5D=0&myparcel_options%5B12405%5D%5Bpackage_type%5D=2&myparcel_options%5B12405%5D%5Binsured_amount%5D=49&myparcel_options%5B12405%5D%5Binsured_amount%5D=0&myparcel_options%5B12188%5D%5Bpackage_type%5D=2&myparcel_options%5B12188%5D%5Binsured_amount%5D=49&myparcel_options%5B12188%5D%5Binsured_amount%5D=0&myparcel_options%5B12184%5D%5Bpackage_type%5D=2&myparcel_options%5B12184%5D%5Binsured_amount%5D=49&myparcel_options%5B12184%5D%5Binsured_amount%5D=0&myparcel_options%5B11981%5D%5Bpackage_type%5D=1&myparcel_options%5B11981%5D%5Binsured_amount%5D=49&myparcel_options%5B11981%5D%5Binsured_amount%5D=0&myparcel_options%5B11974%5D%5Bpackage_type%5D=2&myparcel_options%5B11974%5D%5Binsured_amount%5D=49&myparcel_options%5B11974%5D%5Binsured_amount%5D=0&myparcel_options%5B11840%5D%5Bpackage_type%5D=2&myparcel_options%5B11840%5D%5Binsured_amount%5D=49&myparcel_options%5B11840%5D%5Binsured_amount%5D=0&action2=-1`

**Comment by Spreeuw** [comment]
Zou je even je browser cache kunnen legen?
Dit is als het goed is in 2.0.2 gefixt, maar soms wordt door de browser niet automatisch het script ook vernieuwd.

**Comment by KloonDuino** [comment]
Ik draai MyParcel plugin versie 2.0.5 en verversen en of legen cache van de browser maakt niets uit.
Zowel in Firefox (50.0)  als Chrome ( 54.0.2840.99 m (64-bit))  als IE (> 25) vertonen precies dezelfde melding.

```
Request-URI Too Long

The requested URL's length exceeds the capacity limit for this server.
```

**Comment by Spreeuw** [comment]
Zou je een email willen sturen naar info@drwoo.nl met admin gegevens zodat ik dit op de betreffende site kan bekijken? Ik kan dit hier niet reproduceren met de laatste versie (Edge/Chrome/Firefox).

**Comment by KloonDuino** [comment]
Mooi, het is dus echt opgelost nu?
(we zijn er niet happig op om toegang te geven tot onze backend, het is een life site met gegevens van klanten)

**Comment by Spreeuw** [comment]
Ik heb het probleem hier uiteindelijk ook kunnen reproduceren met een andere klant, het bleek gerelateerd aan de opties voor retourzendingen. Als je de oplossing zelf wilt toepassen, kun je deze versie van het script gebruiken: https://raw.githubusercontent.com/myparcelnl/woocommerce-myparcel/master/assets/js/wcmyparcel-script.js

(plaatsen in wp-content/plugins/woocommerce-myparcel/master/assets/js/wcmyparcel-script.js en je browser cache legen)

Bij die andere klant is het verholpen, maar het blijft zo dat het voor mij niet altijd mogelijk is om iets op te lossen zonder admin toegang, omdat problemen ook vaak site-specifiek zijn. Als het probleem zich toch nog blijft voordoen, kun je dit issue weer openen en dan ontvang ik graag meer informatie!

**Comment by KloonDuino** [comment]
Alleen het .js script vervangen was niet voldoende. Ik heb ook de andere mod uit de commit doorgevoerd en toen werkte het wel naar behoren.
Dank voor de fix.
(het is voor een serieuze webwinkel ook moeilijk om toegang tot de admin te geven)

**Comment by Spreeuw** [comment]
Mooi dat het weer werkt! De JS was de kern van het probleem, maar mooi dat het nu bij jou ook werkt

Serieuze webwinkels hebben een testomgeving en testen plugins daar voor ze op een live site te installeren. Dat adviseer ik met klem aan iedereen die een webwinkel met veel omzet draait!
Verder gaan wij uiteraard vertrouwelijk om met klantgegevens.

**Comment by KloonDuino** [comment]
Zo ken ik er nog wel een paar:
Serieuze leveranciers testen voordat ze software loslaten op niets vermoedende gebruikers ;)

Klaar, we zijn blij dat het weer net zo goed werkt als voor de update.

**Comment by Spreeuw** [comment]
Ter geruststelling: We testen alles hier uitgebreid, voor de 2.0 release hebben we een aantal maanden (!) met een beta panel getest. Maar bijna iedere shop is anders en we kunnen nooit alle combinaties testen.
