### ISSUE TITLE
Possibility to add tracktrace number to order usable meta data

### ISSUE THREAD

**Issue by f3bruary** [myparcelnl/woocommerce-myparcel#13]
Ik zoek naar de mogelijkheid om het track & trace nummer in een order meta field te krijgen. Momenteel zit deze in een array die onderdeel uitmaakt van het verborgen "_myparcel_shipments" meta veld.

Ik gebruik plugins die gebruik kunnen maken van 'beschikbare' order meta velden en deze kunnen gebruiken voor de boekhouding en andere zaken. Ik zou heel graag over de mogelijkheid beschikken om ook het track & trace nummer te kunnen gebruiken.

Is hier een mogelijkheid voor ? Misschien een custom functie ?

**Comment by Spreeuw** [comment]
Een order kan meerdere shipments met verschillende track & trace nummers bevatten, vandaar dat dit niet los staat opgeslagen. Je kunt wel een filter toepassen op `update_post_meta`, om te kijken of myparcel voorbij komt en zo ja, een kopie te maken van de data.

``` php
add_action( 'update_post_meta', 'myparcel_copy_track_trace', 10, 4 );
function myparcel_copy_track_trace( $meta_id, $object_id, $meta_key, $_meta_value ) {
	if ($meta_key == '_myparcel_shipments') {
		$shipments = $_meta_value;
		if ( !empty($shipments) && is_array($shipments) ) {
			$last_shipment = array_pop( $shipments );
			// check if we have a track & trace number
			if (isset($last_shipment['tracktrace'])) {
				// store a copy in the order
				update_post_meta( $object_id, '_myparcel_tracktrace', $last_shipment['tracktrace'] );
			}
		}
	}
}
```

Ik heb deze code getest met 1 order / export, maar kan er verder geen garanties bij geven ;)

Ewout

**Comment by f3bruary** [comment]
Kan deze code aangepast worden voor WooCommerce v3+ ? Het lijkt niet meer te werken voor mij.
