### ISSUE TITLE
Plugin Broken on WC 3.0.7

### ISSUE THREAD

**Issue by f3bruary** [myparcelnl/woocommerce-myparcel#20]
Sinds ik vanochtend heb ge-update naar WC3.0.7 kan ik geen orders meer exporteren.

Enige errors zijn:

`[18-May-2017 11:46:00 UTC] PHP Notice:  Undefined variable: tracktrace_url in /wp-content/plugins/woocommerce-myparcel/includes/views/wcmp-order-shipment-summary.php on line 3`

`[18-May-2017 11:46:00 UTC] PHP Notice:  Undefined index:  in /wp-content/plugins/woocommerce-myparcel/includes/views/wcmp-order-shipment-summary.php on line 5`

**Comment by Spreeuw** [comment]
welke versies (van MyParcel plugin en WC) gebruikte je hiervoor? Ik kan hier zonder problemen exporteren met 3.0.7.

**Comment by f3bruary** [comment]
False Alarm. Hij doet het plots weer. Geen idee waar het aan lag. Had het 10x geprobeerd zonder success. Maar het werkt weer. Sorry voor het ongemak :(
