### ISSUE TITLE
No Delivery Date in Orders List

### ISSUE THREAD

**Issue by f3bruary** [myparcelnl/woocommerce-myparcel#22]
Sommige orders in de orderlijst hebben geen bezorgdatum. Dit kan een probleem worden als het op een specifieke datum geleverd moet worden ipv de volgende werkdag.

![image](https://user-images.githubusercontent.com/5641933/26923962-160c5cbc-4c44-11e7-8075-ae76624e72b0.png)

**Comment by Spreeuw** [comment]
Wanneer een order geen bezorgdatum heeft, is dit altijd de volgende dag, dit betekent simpelweg dat de klant geen keuze heeft gemaakt (of de bezorgopties niet beschikbaar waren voor deze verzendmethode). Kun je dit bevestigen?
