### ISSUE TITLE
ERROR: De geselecteerde orders zijn nog niet naar MyParcel geselecteerd!

### ISSUE THREAD

**Issue by f3bruary** [myparcelnl/woocommerce-myparcel#23]
Ik kan plots geen orders meer exporteren. Ik krijg telkens de melding in de titel. In de order sidebar widget tweemaal pdf icoon (deze laat wel een barcode/3s code zien)

![image](https://user-images.githubusercontent.com/5641933/27251564-a4849052-5349-11e7-8636-345435d82a61.png)

**Comment by Spreeuw** [comment]
Ik kan deze fout niet reproduceren. Misschien was er een tijdelijke storing?

**Comment by f3bruary** [comment]
Het gebeurt niet meer bij nieuwe orders. Blijkbaar alleen bij de 2 orders van die dag. Het blijft ook gebeuren als ik opnieuw exporteer.

Kan voorlopig geclosed worden.
