### ISSUE TITLE
bedrijven buiten de deur houden (alleen particuliere klanten willen we)

### ISSUE THREAD

**Issue by KloonDuino** [myparcelnl/woocommerce-myparcel#9]
Hoi,

Wij zijn een stiching die alleen aan particulieren (de consument) wil leveren. Om dat zo duidelijk mogelijk te maken (meeste bedrijven hebben er schijt aan helaas), verwijderen we de bedrijfsnaam invoer mogelijkheid (dat scheelt aanzienlijk in foutieve bestellingen).

Maar de laatste tijd zijn er zoveel updates dat we het bijna niet meer kunnen bijhouden om de code in `class-wcmp-nlpostcode-fields.php` aan te passen. We krijgen dan ook veel vervelende orders binnen die we weer moeten terugdraaien.
Vraag is dan ook of er niet een permanente mogelijkheid in de plug-in kan worden gemaakt met bijvoorbeeld een vinkje in de MyParcel settings?
Normaal kunnen we onze eigen aanpassingen in de `functions.php` plaatsen, maar helaas werkt dat niet bij de MyParcel plugin (misschien doen we iets fout?).

Om de `selectbox `aan te passen doen we nu het volgende met de hand:

In functie 'public function nl_checkout_fields( $fields, $country, $form )' 
onder

```
// Add house number Suffix
		$fields[$form.'_house_number_suffix'] = array(
			'label'			=> __( 'Suffix', 'wcmyparcel' ),
			// 'placeholder'	=> __( 'Suffix', 'wcmyparcel' ),
			'class'			=> apply_filters( 'nl_custom_address_field_class', array( 'form-row-quart' ), $form, 'house_number_suffix' ),
			'required'		=> false,
		);
```

Dit toevoegen
			
```
$fields[$form.'_company' ]        = array(
				'label'                 => 'Bedrijven',
				'type'					=> 'select',
				'options' => array(' ' => 'xxx doet geen zaken met bedrijven'),
				'placeholder'  		=> __('Company','wc_disable_checkout_fields'),
				'required'              => false,
				'class'      => array('form-row-wide'),
				);

			     $fields[$form.'company' ]        = $fields['shipping_company' ];
```

Hopelijk zie je kans om iets dergelijks in te bouwen.

**Comment by Spreeuw** [comment]
Kun je je `function.php` code hier delen? Dan kan ik kijken wat er fout aan is. Waarschijnlijk hoef je alleen de prioriteit hoger te zetten zodat het filter na myparcel wordt uitgevoerd.

**Comment by KloonDuino** [comment]
We hebben gezocht maar de oude `functions.php` niet meer kunnen vinden. 
Doe eens een gok en geef ons meteen de juiste code please?

**Comment by Spreeuw** [comment]
Als je alleen de bedrijfsnaam velden wilt verwijderen, kan dat met dit filter in functions.php
``` php
add_filter( 'woocommerce_billing_fields', 'woocommerce_checkout_remove_company', 999, 2);
add_filter( 'woocommerce_shipping_fields', 'woocommerce_checkout_remove_company', 999, 2);
function woocommerce_checkout_remove_company( $fields, $country = '') {
    if(isset($fields['billing_company'])) unset($fields['billing_company']);
    if(isset($fields['shipping_company'])) unset($fields['shipping_company']);

    return $fields;
}
```
maar als je liever een dropdown hebt zoals in je voorbeeld:
``` php
add_filter( 'woocommerce_billing_fields', 'woocommerce_checkout_remove_company', 999, 2);
add_filter( 'woocommerce_shipping_fields', 'woocommerce_checkout_remove_company', 999, 2);
function woocommerce_checkout_remove_company( $fields, $country = '') {
	$company_field = array(
		'label'       => 'Bedrijven',
		'type'        => 'select',
		'options'     => array(' ' => 'xxx doet geen zaken met bedrijven'),
		'placeholder' => __('Company','wc_disable_checkout_fields'),
		'required'    => false,
		'class'       => array('form-row-wide'),
	);
	if (isset($fields['billing_company'])) $fields['billing_company'] = $company_field;
	if (isset($fields['shipping_company'])) $fields['shipping_company'] = $company_field;
	return $fields;
}
```
(met prioriteit 20 lukt het waarschijnlijk ook, maar met 999 ben je zeer waarschijnlijk als laatste)

**Comment by Spreeuw** [comment]
@KloonDuino Is het gelukt?

**Comment by Spreeuw** [comment]
@KloonDuino ik was benieuwd of het gelukt is met bovenstaande code!

**Comment by KloonDuino** [comment]
Ja is inderdaad gelukt, we hebben dit weekend proef gedraaid en het werkt inderdaad zoals jij het voordeed.
Weten inmiddels ook waarom onze eigen function.php mod niet werkte, wij hadden de prioriteit helemaal verkeerd gezet.

Bedankt voor je hulp!
